name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      - name: Instalar Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Instalar dependencias
        run: bun install
      
      - name: Construir la web
        run: bun run build
      
      - name: Subir a GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en la web
        id: deployment
        uses: actions/deploy-pages@v4
